### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Moodle-2.0-plugin-for-Panopto#109]
Looking at https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/tree/2017061000-release-candidate . Is there any way to specify proxy details in the latest version of the block. The last version called the parent constructor which allowed you to pass the WSDL options as a second argument but the latest version does not . The only way I see is to set constants in the SessionManagementWsdlClass (https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/master/lib/SessionManagement/SessionManagementWsdlClass.php)  ? 

Regards,
Hittesh Ahuja

**Comment by jmalmsten-panopto** [comment]
Hey,

So is you look in any of the panopto_x_soap_client you should see some lines like this:

e.g. panopto_session_soap_client.php::92
$this->sessionmanagementserviceadd = new SessionManagementServiceAdd(
    array('wsdl_url' => $this->apiurl)
);

You can see I am overriding the default demo.hosted.panopto.com url used by the wsdl files with the new URL that is the current Panopto server.

You can pass a variety of options like this into the wsdl constructor, maybe that has what you need instead of setting the constants in the file itself?

If you need more assistance please open a support ticket with Panopto so I can help you more directly.

Thanks,
Joe M

**Comment by hitteshahuja** [comment]
Hi Joe, Raised a support ticket with more details. It does not seem to work for us. We have set Moodle proxy under HTTP settings and I still get SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://<panoptoinstance>.cloud.panopto.eu/Panopto/PublicAPI/4.6/SessionManagement.svc?wsdl' : failed to load external entity

**Comment by jmalmsten-panopto** [comment]
going to close this since we received the support ticket on Panopto.
