### ISSUE TITLE
Login speed with the new release

### ISSUE THREAD

**Issue by aspark21** [Panopto/Moodle-2.0-plugin-for-Panopto#110]
Have you load tested the v2 release (2017061400) for login speed?

We have upgraded a site a week ago with 65 courses which is a small site really (there's about 500 videos on Panopto throughout all courses the users would have access to) and suddenly the login to the moodle site takes a user consistently 15-17 seconds instead of 1-2 seconds for all other moodle sites on the same server, panopto site & ldap configurations (manual account logins are equally affected by this delay). While they have differing plugin sets, the standout is the difference in Panopto block versions.

I'm still in the process of investigating but the Panopto plugin does seem the most likely cause due to the syncing with the panopto server having been moved to when the user logs in to the site.

**Comment by jmalmsten-panopto** [comment]
There is an increase in login speed, this is because the code needs to build a list of groups/folders the user has access to, and then sends that to Panopto. This will mostly affect admins (or anyone with access to a lot of courses, especially if multiple Panopto servers are used on the Moodle instance).

If you select "Asynchronous enrollment sync" the login task should be done in the background, there might be a slight delay for the permissions to sync since this is being done in the background then.

If you are experiencing this delay for students as well, or wish to get further assistance could you please open a ticket with Panopto and our support with gladly help you.

**Comment by aspark21** [comment]
N.B. Slow login issue was not related to the Panopto plugin.

**Comment by jmalmsten-panopto** [comment]
Hi Alistair,

We're glad to hear your issue has been cleared up! If you have any other questions or need any help with Panopto feel free to contact us again.

Thanks,
Joe M
