### ISSUE TITLE
Exception : SOAP-ERROR : Parsing WSDL : Couldn't load from

### ISSUE THREAD

**Issue by aurelienb1** [Panopto/Moodle-2.0-plugin-for-Panopto#183]
Hi,

The Panopto LTI configuration is functional, but the block always gives me a SOAP error 

**Exception : SOAP-ERROR : Parsing WSDL : Couldn't load from 'https://XXXXXXXX/Panopto/PublicAPI/4.6/SessionManagement.svc?singlewsdl' : failure to load the external entity "https://XXXXXXXX/Panopto/PublicAPI/4.6/SessionManagement.svc?singlewsdl".** 

Our servers reach Panopto fine because the LTI is working, but when I click on _Provision course_ in the block, after a few seconds I get the SOAP error.

Do you have any idea?

Regards

**Comment by jmalmsten-panopto** [comment]
Hi,

I would suggest trying to connect your Moodle environment and from there see if you can ping or curl your Panopto server. When I see that issue it's usually because the Moodle server can't communicate with the Panopto environment in some form. 

If you need any assistance after that I would suggest opening a support ticket with Panopto at [https://support.panopto.com](https://support.panopto.com), they can give you more assistance and respond faster than I can. 

Thanks,
Joe Malmsten
