### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by sharpchi** [Panopto/Moodle-2.0-plugin-for-Panopto#197]
Moodle's latest 4.1.x release says that it's compatible with PHP 8.1 (it's targeting PHP 8.2 for Moodle 4.2). I thought I'd give PHP 8.1 a blast and got the attached deprecation notices that were thrown by the Panopto block

Version: 2023031400
Moodle 4.1.2

[panopto-deprecation-php81.txt](https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/files/11017476/panopto-deprecation-php81.txt)

Hope it's of use, thanks.

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for reporting this issue to us. I have filed an internal work item and we will take a look.

Thanks,
Joe

**Comment by slewislcm** [comment]
Hi, 
Any update on this at all? Will it be fixed in an updated version of the plugin (and if so is there a release date for this).
We'd like to use PHP 8.1 for next year's moodle from September onwards, and at that moment I can't tell if these errors are stopping panopto block working completely or not (as it's just a test site), which would be a critical factor in deciding whether to use PHP8.1 or not.
thanks, 
Simon

**Comment by jmalmsten-panopto** [comment]
Hi,

At this time we have not tested PHP 8.1 yet and we do not have an ETA on when we will be testing PHP 8.1 compatibility with the block. 

Thanks,
Joe

**Comment by acquaalta** [comment]
Hi,
1. According to that page:
https://moodle.org/plugins/block_panopto
The plugin supports Moodle 4.1
When a plugin creator declares that the plugin supports a Moodle version, it's expected that the plugin would support the PHP versions that the Moodle version officially supports. 
Since the Moodle 4.1.2 release (13 March 2023), Moodle supports PHP 8.1
Please keep in line with Moodle and release a new version of the plugin that supports PHP 8.1

2. Please also note that at this point each other company that I contacted regarding PHP 8.1 support already added it upon my and I guess other clients request. 

3. **Do the deprecations mentioned originally in this issue actually harm the functionality of the plugin? Or we can still use the current version of the plugin although it doesn't officially supports PHP 8.1 yet?

Thanks

**Comment by sharpchi** [comment]
Security support for PHP8.0 ends in November 2023, so this doesn't really allow us much time before IT starts to get jittery and will be pushing for Server upgrades. Plus we need to schedule these downtimes around the academic calendar. Ideally, I'd like to see this block supported to PHP8.2.
![image](https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/assets/3774280/499c6292-68e9-4c28-ad56-d68e6208e708)

**Comment by zeroAps** [comment]
This is resolved in [2023091800](https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/releases/tag/2023091800) release. Closing this for now. Thanks
