### ISSUE TITLE
block_panopto_foldermap has empty fields in a new course with the block. Can't provision

### ISSUE THREAD

**Issue by Syxton** [Panopto/Moodle-2.0-plugin-for-Panopto#59]
Can't provision the course from the Panopto block because it doesn't pass the if statement in edit_form.php line ~46
```
if (!empty($panoptodata->servername) && !empty($panoptodata->instancename) && !empty($panoptodata->applicationkey)) {
```
To get around this issue I placed the following code in panopto_data.php after line 73
```
if (isset($moodlecourseid)) {
            $this->servername = self::get_panopto_servername($moodlecourseid);
            $this->applicationkey = self::get_panopto_app_key($moodlecourseid);
```
i added
```
// fill in the blank fields
if(empty($this->servername) || empty($this->applicationkey)){
                $this->servername = self::set_panopto_server_name($moodlecourseid, $CFG->block_panopto_server_name1);
                $this->applicationkey = self::set_panopto_app_key($moodlecourseid, $CFG->block_panopto_application_key1);
            }
```

Obviously this isn't code that should be considered a fix because it is hardcoded to server_name1 and application_key1.

**Comment by Syxton** [comment]
Is anyone else have this issue?

**Comment by Syxton** [comment]
Just did a fresh install of the Panopto block.  I'm still getting an error of 
"Cannot configure block instance: Global configuration incomplete. Please contact your system administrator."  it works perfectly if I add the code above

**Comment by plancaster-panopto** [comment]
Hi @Syxton,
Thank you for bringing this issue to our attention. As it turns out, the problem you were encountering was due to panopto_content.php attempting to return the link to provision a new course when it has not been provisioned rather than echoing it, as it should. This issue has now been fixed in [the latest commit](https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/commit/9c5f5992ffc0ee4766c3dc5b8623e9c66d901d82), and the issue should be resolvedl.

**Comment by Syxton** [comment]
that's great.  Thanks!

**Comment by Hiroshi-p** [comment]
I assume this problem was fixed. Closing this entry.
