### ISSUE TITLE
I get the following Notice

### ISSUE THREAD

**Issue by sleitao** [Panopto/Moodle-2.0-plugin-for-Panopto#68]
Notice: Undefined property: stdClass::$block_panopto_server_number in /var/www/html/moodle/blocks/panopto/settings.php on line 25

**Comment by sleitao** [comment]
Moodle 2.7
Panopto block version - 2016032401

**Comment by Hiroshi-p** [comment]
We track this our internal work item 41908 and will fix it.

**Comment by Hiroshi-p** [comment]
We internally tested plug-in 2016081900 Release with Moodle 3.1 and this problem did not repro.
Please feel free to reopen this if anyone sees this problem with latest Moodle + latest plug-in.

**Comment by agrowe** [comment]
@Hiroshi-p This issue is still here in Moodle 3.1.3 and block version 2016102400

It's not the "exact" same issue but is still because the `settings.php` file is including the `version.php` file unnecessarily.

Here is the error we are getting when browsing to /admin/tool/replace/index.php with debugging turned on.
```
Warning: Creating default object from empty value in SITEDIR/admin/tool/replace/version.php on line 28
```

Here is the stack trace too
```
( ! ) Warning: Creating default object from empty value in C:\wamp\www\moodle\moodle31\admin\tool\replace\version.php on line 28
Call Stack
#	Time	Memory	Function	Location
1	0.0005	254840	{main}( )	..\index.php:0
2	0.1747	27538592	admin_externalpage_setup( )	..\index.php:31
3	0.1773	27555792	admin_get_root( )	..\adminlib.php:7164
4	0.4399	33668576	require( 'C:\wamp\www\moodle\moodle31\admin\settings\plugins.php' )	..\adminlib.php:7279
5	0.6497	44351336	core\plugininfo\block->load_settings( )	..\plugins.php:63
6	0.6549	44744088	include( 'C:\wamp\www\moodle\moodle31\blocks\panopto\settings.php' )	..\block.php:99
7	0.6554	44746848	require( 'C:\wamp\www\moodle\moodle31\admin\tool\replace\version.php' )	..\settings.php:25
```

Can the plugin be changed so that it does not bring in the version number at all in the settings page? No other plugin does this as the version is easily accessible in the plugins overview or the manage activities page.

It's annoying that we need to delete this from every version of Panopto we install.

**Comment by Hiroshi-p** [comment]
Thank you for the report. We'll take a second look.

**Comment by agrowe** [comment]
In the meantime, we have done the following:

Comment out `require('version.php');` on line 25

Change `$currversion` on line 32 to be `$currversion = 2016102400;` which is the version from `version.php`

**Comment by jmalmsten-panopto** [comment]
In the upcoming release this should be taken care of, there is no reference to the version or version.php file in the settings anymore.

If you wish to see the version of the Panopto block after the release you will need to go to:
Site Administration -> plugins -> blocks -> manage blocks
This now uses the standard way to check versions in moodle plug ins. 

Thanks for your feedback, if this problem persists in the future please contact us again.
