### ISSUE TITLE
Moodle 3.2 compatibility - SOAP WSDL errors - PHP Fatal errors

### ISSUE THREAD

**Issue by aspark21** [Panopto/Moodle-2.0-plugin-for-Panopto#81]
Moodle: 3.2 latest stable
Panopto: master branch 

"PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https:///Panopto/PublicAPI/4.0/Auth.svc?wsdl' : failed to load external entity "https:///Panopto/PublicAPI/4.0/Auth.svc?wsdl"
 in /home/travis/build/aspark21/moodle/blocks/panopto/lib/panopto_auth_soap_client.php on line 52"

https://travis-ci.org/aspark21/moodle/jobs/189214876#L1542

**Comment by Hiroshi-p** [comment]
@aspark21 
Thank you for reporting the issue. We tested the scenario with the said version, but it did not repro. We inspected the code history, but we don't have any change that may directly cause this issue.
I think this is related to the initial configuration around Panopto server and Moodle server.
Please report this issue with the support channel between your organization and Panopto support team so that we will work directly with you for troubleshooting.

**Comment by jmalmsten-panopto** [comment]
Hey,

looks like in your travisCI log I see the attempt to get the Auth.svc as:

https:///Panopto/PublicAPI/4.0/Auth.svc?wsdl

I believe this means the server name you have set in the panopto block config is "/Panopto", it needs to be the URL to your panopto server.

**Comment by aspark21** [comment]
@Hiroshi-p this is breaking the PHPUnit tests. It may indeed work fine in a production environment.

Can't something be changed to ensure the unit tests run properly out of the box? It's hard to tell wether a plugin is ready for a new version of Moodle in this state. 

We run all our plugins through CI ahead of moodle upgrades in order to catch any issues - more efficient than human testing with wider coverage. This plugin is the only one which doesn't run these properly & affects the tests of all other plugins. It is a problem for anyone with a CI/CD strategy for Moodle.

**Comment by Hiroshi-p** [comment]
@aspark21 Thank you for the clarification. Our plug-in requires valid Panopto server to run. I am not 100% sure your definition of "out of the box" and we need to learn your workflow of testing and configuration in order to answer your question.
May I ask you to report this issue through support channel, so that we may discuss directly about this further. It would be helpful to point out this GitHub issue when you open the support ticket.
