### ISSUE TITLE
Validation failure while updating from 2017032203 to 2017061000

### ISSUE THREAD

**Issue by ozanvarli** [Panopto/Moodle-2.0-plugin-for-Panopto#99]
Downloading block_panopto ... OK
Validating block_panopto ... Error
  [Error] Plugin does not declare its version [null] 
Installation aborted due to validation failure

**Comment by hohno-panopto** [comment]
Thank you for the report. We are investigating.

**Comment by jmalmsten-panopto** [comment]
Hey,

Thank you for bringing this to our attention.

I updated the code to pass the validation when installing through the UI. Could you try again and re-open if you still experience this issue?

Thanks,
Joe M

**Comment by ozanvarli** [comment]
Thanks for the quick fix, works fine now!

**Comment by ozanvarli** [comment]
![snip20170613_1](https://user-images.githubusercontent.com/23216941/27068297-0312ebee-5018-11e7-82d7-386505b0942d.png)

Debug info: Table '_databasename_.mdl_block_panopto_old_foldermap' doesn't exist
INSERT INTO mdl_block_panopto_old_foldermap () VALUES ()
[array (
)]
Error code: dmlwriteexception
×Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1342 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1309 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_chunk()
line 1019 of /blocks/panopto/lib/panopto_data.php: call to mysqli_native_moodle_database->insert_records()
line 302 of /blocks/panopto/db/upgrade.php: call to panopto_data::delete_panopto_relation()
line 925 of /lib/upgradelib.php: call to xmldb_block_panopto_upgrade()
line 434 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 683 of /admin/index.php: call to upgrade_noncore()

**Comment by jmalmsten-panopto** [comment]
Hi,

Have a fix for this and will release it shortly. 

Thanks for your patience,
Joe M

**Comment by jmalmsten-panopto** [comment]
Ok, you can try now.

Joe M

**Comment by ozanvarli** [comment]
Joe, thanks a lot for the effort you have put in this so far, but it seems that there are still some issues with the code:

![image](https://user-images.githubusercontent.com/23216941/27222556-63c8a814-5295-11e7-9c6e-6d72ee353482.png)

**Comment by jmalmsten-panopto** [comment]
Hey,

You have reached an expected error. Please see the 'Preparation' section of this doc from the release notes:
https://support.panopto.com/articles/Documentation/Moodle-Plugin-Upgrade-2017-2017061000

This is because the Moodle block needs to re-provision every existing folder against the new server code, we make sure the user performing the upgrade has at least viewer permission on each folder (or an Administrator on Panopto)  before actually performing the upgrade.

To get around this follow the steps listed in the document above, then the upgrade should continue as it should.

Thanks,
Joe M

**Comment by ozanvarli** [comment]
I see, thanks!
